### ISSUE TITLE
arm64 cross-compilation with go broken

### ISSUE THREAD

**Issue by joemiller** [buildkite/elastic-ci-stack-for-aws#1147]
**Describe the bug**
I have been attempting to use chainguard's melange tool to cross-compile amd64 and arm64 packages but have been running into issues with the arm64 builds that look roughly like
```
2023-06-27T23:30:09Z] 2023/06/27 23:30:09 melange (example/aarch64): go: downloading github.com/sirupsen/logrus v1.9.0
[2023-06-27T23:30:09Z] 2023/06/27 23:30:09 melange (example/aarch64): runtime: newstack sp=0x4000a00b80 stack=[0x140001b4000, 0x140001b8000]
[2023-06-27T23:30:09Z] 2023/06/27 23:30:09 melange (example/aarch64): 	morebuf={pc:0x497cc sp:0x4000a00b80 lr:0x0}
[2023-06-27T23:30:09Z] 2023/06/27 23:30:09 melange (example/aarch64): 	sched={pc:0x5ba8c sp:0x4000a00b80 lr:0x497cc ctxt:0x0}
[2023-06-27T23:30:09Z] 2023/06/27 23:30:09 melange (example/aarch64): runtime: gp=0x140001a0d00, goid=19, gp->status=0x2
[2023-06-27T23:30:09Z] 2023/06/27 23:30:09 melange (example/aarch64):  runtime: split stack overflow: 0x4000a00b80 < 0x140001b4000
```
or sometimes simply:
```
[2023-06-27T23:40:57Z] 2023/06/27 23:40:57 melange (example2/aarch64): go: downloading github.com/sirupsen/logrus v1.9.0
[2023-06-27T23:40:57Z] 2023/06/27 23:40:57 melange (example2/aarch64): Segmentation fault (core dumped)
```

I see that support for cross builds was added to the stack in https://github.com/buildkite/elastic-ci-stack-for-aws/pull/903/files

I am able to resolve the issue by running the following in a pre-command hook:
```
docker run --rm --privileged --userns host multiarch/qemu-user-static --reset -p yes
```
I haven't tried running this from a `BootstrapScriptUrl` yet. I suspect it would be fine.

I am wondering if an update of the qemu + binfmt hooks should go into the CFN stack, however?

**Steps To Reproduce**
NOTE: This is likely not a full reproduction as the steps in my actual workflow are a bit complicated. They could be run directly on the host to reproduce more quickly.

```yaml
# example.yaml
package:
  name: example
  version: 0.0.1
  description: example package
  target-architecture:
    - all
  copyright:
    - license: Apache-2.0
      paths:
        - "*"

environment:
  contents:
    repositories:
      - https://packages.wolfi.dev/os
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    packages:
      - ca-certificates-bundle
      - busybox
      - go

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/puerco/hello.git
      destination: build-dir

  - run: |
      git checkout ${{package.version}}

  - uses: go/build
    with:
      modroot: build-dir
      tags: enterprise
      packages: ./main.go
      output: hello
```
```console
# docker-compose.yml
version: '2.1'

services:
  melange:
    build:
      context: .
      dockerfile: Dockerfile.melange
    volumes:
      - .:/work
    working_dir: /work
    # melange uses bubblewrap to create namespaces:
    privileged: true
    userns_mode: 'host'
```
```
# Dockerfile.melange
# # syntax=docker/dockerfile:1.4

FROM cgr.dev/chainguard/melange:latest AS melange

FROM alpine:3.17

RUN apk --no-cache add \
      ruby \
      bubblewrap

COPY --from=melange /usr/bin/melange /usr/bin/melange
```

from the host:
```console
docker compose run melange melange build --arch aarch64 example.yaml
```

**Stack parameters (please complete the following information):**
 - AWS Region: us-east-1
 - Version: v5.21.0
