### ISSUE TITLE
Support configuring the log retention for the autoscaling stack

### ISSUE THREAD

**Issue by grahamc** [buildkite/elastic-ci-stack-for-aws#1277]
**Describe the bug**

The stack creates a log group with a retention of 1 day, by nesting the serverless function https://github.com/buildkite/buildkite-agent-scaler/blob/master/template.yaml#L83-L86

```
LogRetentionDays:
    Type: Number
    Description: The number of days to retain the Cloudwatch Logs of the lambda.
    Default: "1"
```

This parameter can't be adjusted, and I think the only lift is to expose this option and forward it.

**Steps To Reproduce**

1. Enable the stack.
2. Check the log retention.

**Expected behavior**

Configurable log retention.

**Actual behaviour**

Static, 1 d retention.

**Stack parameters (please complete the following information):**
 - AWS Region: us-east-2
 - Version v6.12.0

**Additional context**
n/a
