### ISSUE TITLE
Intermittent docker error "could not find an available predefined network"

### ISSUE THREAD

**Issue by zain** [buildkite/elastic-ci-stack-for-aws#148]
I see these on builds occasionally:

```
$ docker-compose -f docker-compose.yml -p buildkite9c0e505a3f5844e4bde33ee36c928627 run node pug-lint app/assets/javascripts
Creating network "buildkite9c0e505a3f5844e4bde33ee36c928627_default" with the default driver
ERROR: failed to parse pool request for address space "LocalDefault" pool "" subpool "": could not find an available predefined network
```

Here's the Dockerfile I'm using:

```
FROM node:4.5.0

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

COPY package.json /usr/src/app/

RUN npm install
RUN npm install -g eslint babel-eslint pug-lint

COPY . /usr/src/app
```

and the pipeline.yml:

```
steps:
  - name: ":docker:"
    plugins:
      docker-compose:
        build: node

  - wait

  - name: ":eslint:"
    command: "eslint --cache app/assets/javascripts spec/javascripts"
    plugins:
      docker-compose:
        run: node

  - name: ":dog:"
    command: "pug-lint app/assets/javascripts"
    plugins:
      docker-compose:
        run: node
```

**Comment by lox** [comment]
I'd suggest you change those docker registry credentials now ;)

**Comment by lox** [comment]
Perhaps related to this docker issue? https://github.com/docker/docker/issues/23971

**Comment by keithpitt** [comment]
@lox already done :)

**Comment by lox** [comment]
On reading the above issue a bit more, looks like there is a limit on the number of networks created, I wonder if we are not correctly cleaning up after builds with `docker-compose down`

**Comment by zain** [comment]
Running this fixes the issue, but it's not really a solution because I can't just constantly be running this. `docker network ls | awk '{print $1}' | xargs docker network rm`

**Comment by lox** [comment]
Which version of the stack are you seeing this in @zain? I don't have much experience with the docker-compose plugin, as it's not in the stable release. It does look to me like the networks aren't being cleaned up after each command.

**Comment by lox** [comment]
Perhaps @sj26 might know.

**Comment by sj26** [comment]
There is docker-compose support in the stable version using environment variables. :-)

We are running `docker-compose down` at the end of builds which should also remove any created networks:

https://github.com/buildkite/agent/blob/2-2-stable/templates/bootstrap.sh#L498-L499

We also run it in plugin (used by the beta agent):

https://github.com/buildkite-plugins/docker-compose-buildkite-plugin/blob/master/hooks/commands/run.sh#L43

But perhaps it might be worth looking at previous builds to see if this command is throwing errors? It's done in cleanup in a collapsed build log section so I don't think its exit status changes the build status and it might not be super visible.

We also suffer from this problem! Although I had absolutely no idea what those errors meant. docker-compose should probably be throwing more descriptive errors when this happens.

**Comment by zain** [comment]
Our CI server goes for less than a day before all builds start erroring out with this message. I'm using the unstable version of the buildkite-agent (v3.0-beta.9). Here's the pipeline.yml that is currently causing this error: 

```yml
steps:
  - name: ":docker:"
    plugins:
      docker-compose:
        build: web
    agents:
      queue: big
  - wait
  - name: ":rspec:"
    command: .buildkite/scripts/run-rspec.sh
    plugins:
      docker-compose:
        run: web
    parallelism: 16
    agents:
      queue: big
```

and the `run-rspec.sh` script:
```bash
#!/bin/bash

set -eo pipefail

.buildkite/scripts/wait-for-it.sh -t 600 db:5432
bundle exec rake db:create knapsack_pro:rspec SPEC_OPTS="--tag ~js"
```

This is pretty much a blocker for us to be able to use buildkite, so hoping you guys have some more insight here.

**Comment by zain** [comment]
This might shed some light. This is our docker-compose.yml:

```yml
version: '2'

services:
  db:
    image: mdillon/postgis:9.4
  elasticsearch:
    image: elasticsearch:2.3
  web:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
      - elasticsearch
```

And the output of `$ docker ps` is a huge list of `mdillon/postgis:9.4` and `elasticsearch:2.3` containers.
