### ISSUE TITLE
spot price and fallback asg support

### ISSUE THREAD

**Issue by tnh** [buildkite/elastic-ci-stack-for-aws#361]
something I have done is my forked version of the stack is to build a second set of resources for
- scale up monitor
- scale up event
- scale down monitor
- scale down event
- asg
- launch config
that doesn't contain Spot price.

the logic being, fall back to an on demand instance if the spot price cannot be met.

**Comment by tnh** [comment]
```
Condition:
  UseSpotASGBackup: !And [ !Not [!Equals [!Ref 'MaxSize', !Ref 'MinSize']], !Not [!Equals [!Ref 'SpotPrice', 0]]]
```
with
```
  AgentScaleUpPolicyBackup:
    Type: AWS::AutoScaling::ScalingPolicy
    Condition: UseSpotASGBackup
    Properties:
      AdjustmentType: ChangeInCapacity
      AutoScalingGroupName: !Ref 'AgentAutoScaleGroupBackup'
      Cooldown: 300
      ScalingAdjustment: !Ref 'ScaleUpAdjustment'
  AgentScaleUpPolicyBackup:
    Type: AWS::AutoScaling::ScalingPolicy
    Condition: UseSpotASGBackup
    Properties:
      AdjustmentType: ChangeInCapacity
      AutoScalingGroupName: !Ref 'AgentAutoScaleGroupBackup'
      Cooldown: 300
      ScalingAdjustment: !Ref 'ScaleUpAdjustment'
  AgentScaleDownPolicyBackup:
    Type: AWS::AutoScaling::ScalingPolicy
    Condition: UseAutoscaling
    Properties:
      AdjustmentType: ChangeInCapacity
      AutoScalingGroupName: !Ref 'AgentAutoScaleGroup'
      Cooldown: 300
      ScalingAdjustment: !Ref 'ScaleDownAdjustment'
  AgentUtilizationAlarmHighBackup:
    Type: AWS::CloudWatch::Alarm
    Condition: UseSpotASGBackup
    Properties:
      AlarmDescription: Scale-up if ScheduledJobs > 0 for 5 minute
      MetricName: ScheduledJobsCount
      Namespace: Buildkite
      Statistic: Minimum
      Period: 60
      EvaluationPeriods: 5
      Threshold: 0
      AlarmActions:
        - !Ref 'AgentScaleUpPolicyBackup'
      Dimensions:
        - Name: Queue
          Value: !Ref 'BuildkiteQueue'
      ComparisonOperator: GreaterThanThreshold
  AgentUtilizationAlarmLowBackup:
    Type: AWS::CloudWatch::Alarm
    Condition: UseSpotASGBackup
    Properties:
      AlarmDescription: Scale-down if UnfinishedJobs == 0 for N minutes
      MetricName: UnfinishedJobsCount
      Namespace: Buildkite
      Statistic: Maximum
      Period: !Ref 'ScaleDownPeriod'
      EvaluationPeriods: 1
      Threshold: 0
      AlarmActions:
        - !Ref 'AgentScaleDownPolicyBackup'
      Dimensions:
        - Name: Queue
          Value: !Ref 'BuildkiteQueue'
      ComparisonOperator: LessThanOrEqualToThreshold
  AgentLaunchConfigurationBackup:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      AssociatePublicIpAddress: !Ref 'AssociatePublicIpAddress'
      SecurityGroups:
        - !If [CreateSecurityGroup, !Ref 'SecurityGroup', !Ref 'SecurityGroupId']
      KeyName: !Ref 'KeyName'
      IamInstanceProfile: !Ref 'IAMInstanceProfile'
      InstanceType: !Ref 'InstanceType'
      ImageId: !If [UseDefaultAMI, !FindInMap [AWSRegion2AMI, !Ref 'AWS::Region',
          AMI], !Ref 'ImageId']
      BlockDeviceMappings:
        - DeviceName: /dev/xvda
          Ebs:
            VolumeSize: !Ref 'RootVolumeSize'
            VolumeType: gp2
      UserData: !Base64
        Fn::Sub:
          - "#!/bin/bash -xv\nBUILDKITE_STACK_NAME=\"${AWS::StackName}\" \\\nBUILDKITE_STACK_VERSION=v2.3.1\
            \ \\\nBUILDKITE_SECRETS_BUCKET=\"${LocalSecretsBucket}\" \\\nBUILDKITE_AGENT_TOKEN=\"\
            ${BuildkiteAgentToken}\" \\\nBUILDKITE_AGENTS_PER_INSTANCE=\"${AgentsPerInstance}\"\
            \ \\\nBUILDKITE_AGENT_TAGS=\"${BuildkiteAgentTags}\" \\\nBUILDKITE_AGENT_RELEASE=\"\
            ${BuildkiteAgentRelease}\" \\\nBUILDKITE_QUEUE=\"${BuildkiteQueue}\" \\\
            \nBUILDKITE_ELASTIC_BOOTSTRAP_SCRIPT=\"${BootstrapScriptUrl}\" \\\nBUILDKITE_AUTHORIZED_USERS_URL=\"\
            ${AuthorizedUsersUrl}\" \\\nBUILDKITE_ECR_POLICY=${ECRAccessPolicy} \\\
            \nBUILDKITE_LIFECYCLE_TOPIC=${AgentLifecycleTopic} \\\nAWS_DEFAULT_REGION=${AWS::Region}\
            \ \\\nSECRETS_PLUGIN_ENABLED=${EnableSecretsPlugin} \\\nECR_PLUGIN_ENABLED=${EnableECRPlugin}\
            \ \\\nDOCKER_LOGIN_PLUGIN_ENABLED=${EnableDockerLoginPlugin} \\\nDOCKER_USERNS_REMAP=${EnableDockerUserNamespaceRemap}\
            \ \\\nAWS_REGION=${AWS::Region} \\\n  /usr/local/bin/bk-install-elastic-stack.sh\n"
          - LocalSecretsBucket: !If [CreateSecretsBucket, !Ref 'ManagedSecretsBucket',
              !Ref 'SecretsBucket']
  AgentLifecycleHookBackup:
    Type: AWS::AutoScaling::LifecycleHook
    Properties:
      AutoScalingGroupName: !Ref 'AgentAutoScaleGroupBackup'
      LifecycleTransition: autoscaling:EC2_INSTANCE_TERMINATING
      DefaultResult: CONTINUE
      HeartbeatTimeout: 120
      NotificationTargetARN: !Ref 'AgentLifecycleTopic'
      RoleARN: !GetAtt 'AgentLifecycleHookRole.Arn'
  AgentAutoScaleGroupBackup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      VPCZoneIdentifier: !If [CreateVpcResources, [!Ref 'Subnet0', !Ref 'Subnet1'],
        !Ref 'Subnets']
      LaunchConfigurationName: !Ref 'AgentLaunchConfigurationBackup'
      MinSize: !Ref 'MinSize'
      MaxSize: !Ref 'MaxSize'
      MetricsCollection:
        - Granularity: 1Minute
          Metrics:
            - GroupMinSize
            - GroupMaxSize
            - GroupInServiceInstances
            - GroupTerminatingInstances
            - GroupPendingInstances
      TerminationPolicies:
        - OldestLaunchConfiguration
        - ClosestToNextInstanceHour
      Tags:
        - Key: Role
          Value: buildkite-agent
          PropagateAtLaunch: true
        - Key: Name
          Value: buildkite-agent
          PropagateAtLaunch: true
        - Key: BuildkiteAgentRelease
          Value: !Ref 'BuildkiteAgentRelease'
          PropagateAtLaunch: true
        - Key: BuildkiteQueue
          Value: !Ref 'BuildkiteQueue'
          PropagateAtLaunch: true
```
Love to see if something like this could be added in
