### ISSUE TITLE
Preemptively start new instances for jobs waiting down the pipeline

### ISSUE THREAD

**Issue by arturopie** [buildkite/elastic-ci-stack-for-aws#397]
In our current setup, we have a step for building the test docker image, and then we have a parallelized step for running our tests.

Currently, if there are no instances up, those parallelized jobs could be waiting for up to 3 minutes. 

I wonder if we could detect how many jobs are going to be waiting once the current step is done, and start warming those instances up preemptively.

Here is an example of the pipeline I'm describing:

```
steps:
  - name: ':docker:'
    plugins:
      docker-compose#v1.8.4:
        build: app_test
        image-repository: registry/app_test
  - wait

  - name: ':firefox:'
    command: 'run_tests.sh'
    parallelism: 32
    plugins:
      docker-compose#v1.8.4:
        run: app_test
        image-repository: registry/app_test
        env:
          - BUILDKITE_PARALLEL_JOB
          - BUILDKITE_PARALLEL_JOB_COUNT
```
