### ISSUE TITLE
JAVA_HOME is not set and no 'java' command could be found in your PATH

### ISSUE THREAD

**Issue by Allan-Gong** [buildkite/elastic-ci-stack-for-aws#501]
Building an app using docker(java + node) with buildkite.

The build and deploy works fine locally, in a docker container. But failed in buildkite agent with the following error:
ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.
  |  
  | Please set the JAVA_HOME variable in your environment to match the
  | location of your Java installation.

Docker file used:

```
FROM openjdk:8-jre

# Install node 10
RUN set -x \
    && curl -sL https://deb.nodesource.com/setup_10.x | bash - \
    && apt-get install -y \
        nodejs \
    && npm install -g npm@latest yarn@latest
```

Couldn't figure out what went wrong. Please help ?

**Comment by Allan-Gong** [comment]
Hi Tim,

I am definitely running the commands within a docker container.

The weirdest thing is that it runs fine on my local machine but failed in buildkite agent ...

Below is the command I run:

```
docker-compose run --rm deploy \
	npm install \
	&& ./gradlew clean check build -PartifactoryUsername=readonly -PartifactoryPassword=$ARTIFACTORY_TOKEN \
	&& serverless deploy --stage prod --verbose
```
 
Not sure what I did wrong ...

I have attached the step log if you can take a look
[ai-cf-deepmatch-application-score-lambda_build_61_docker-deploy-to-production.log](https://github.com/buildkite/elastic-ci-stack-for-aws/files/2570639/ai-cf-deepmatch-application-score-lambda_build_61_docker-deploy-to-production.log)

**Comment by toolmantim** [comment]
Thanks @Allan-Gong. What does your pipeline.yml for the step look like?

**Comment by Allan-Gong** [comment]
pipeline:
```
- label: ':docker: deploy to production'
  plugins:
    seek-oss/aws-sm#v0.0.5:
      env:
        ARTIFACTORY_TOKEN: artifactory/read-only-token
  branches: "master"
  command: make deploy
  agents:
    queue: 'deepmatch-prod:cicd'
  concurrency: 1
  concurrency_group: 'deepmatch-application-score-lambda/deploy-prod'
```

Makefile:

```
deploy:
	docker-compose run --rm deploy \
	npm install \
	&& ./gradlew clean check build -PartifactoryUsername=readonly -PartifactoryPassword=$$ARTIFACTORY_TOKEN \
	&& serverless deploy --stage prod --verbose
```
