### ISSUE TITLE
Updating the AMI using SSM instead of by filling in the AWSRegion2AMI mapping

### ISSUE THREAD

**Issue by nitrocode** [buildkite/elastic-ci-stack-for-aws#717]
Instead of the mapping, SSM can be used to store the value of the latest AMI and then retrieved from the cloudformation template.

See: https://aws.amazon.com/blogs/compute/query-for-the-latest-amazon-linux-ami-ids-using-aws-systems-manager-parameter-store/

Excerpt (example):

```
# Use public Systems Manager Parameter
Parameters:
  LatestAmiId:
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: '/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2'

Resources:
 Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: !Ref LatestAmiId
```
