### ISSUE TITLE
v5.0.0 stack cloudformation template incomplete

### ISSUE THREAD

**Issue by jufemaiz** [buildkite/elastic-ci-stack-for-aws#757]
https://s3.amazonaws.com/buildkite-aws-stack/v5.0.0/aws-stack.yml

```yaml
...
  # Generated from Makefile via build/mappings.yml
  AWSRegion2AMI:
    us-east-1 : { linux: ami-0a196d0aa9a8cdf17, windows: ami-0cb9b5cd847093398 }
...
```

[v5.0.0-beta1](https://s3.amazonaws.com/buildkite-aws-stack/v5.0.0-beta1/aws-stack.yml) had the following:

```yaml
...
  # Generated from Makefile via build/mappings.yml
  AWSRegion2AMI:
    us-east-1 : { linux: ami-09c7f480951700578, windows: ami-0266bfd271b2fc5f7 }
    us-east-2 : { linux: ami-03bad1d2d9d4eeabf, windows: ami-080ad5b40df0fe1f4 }
    us-west-1 : { linux: ami-0f72ad0b55c26e3cf, windows: ami-0dd2c55e23c153469 }
    us-west-2 : { linux: ami-039454969c50522d2, windows: ami-0953ebe1b2965d36e }
    af-south-1 : { linux: ami-0c4dd1164f3c92f12, windows: ami-084c26605455cd0bf }
    ap-east-1 : { linux: ami-0886e04eb21ff9e12, windows: ami-04d00fc929ffaf7d2 }
    ap-south-1 : { linux: ami-03c62c3f2c5c9d8ab, windows: ami-083cfebb8d9afa4ff }
    ap-northeast-2 : { linux: ami-0b79857a0fe304390, windows: ami-0c4a6d697ca0c76a1 }
    ap-northeast-1 : { linux: ami-0c35223c41fab7780, windows: ami-05012d3112f94a9c5 }
    ap-southeast-2 : { linux: ami-09e6e9ac7897f944f, windows: ami-0bc521847edd27365 }
    ap-southeast-1 : { linux: ami-06f1f2d57e130df19, windows: ami-0d1ca4534590e7029 }
    ca-central-1 : { linux: ami-0b2c27d63b7558308, windows: ami-06ca554d36765545a }
    eu-central-1 : { linux: ami-041563bd8440781eb, windows: ami-06f2b90593b4f425b }
    eu-west-1 : { linux: ami-0acc701c3e67c8b83, windows: ami-06139361f29c00f15 }
    eu-west-2 : { linux: ami-09ba50f67db8894f1, windows: ami-0c8bbaedc4653ad78 }
    eu-south-1 : { linux: ami-07e7a93a9a8b47480, windows: ami-07a648a7375338975 }
    eu-west-3 : { linux: ami-0e67bea8eb8f5febb, windows: ami-0a7ea7926fd1bba28 }
    eu-north-1 : { linux: ami-079674015758e7d69, windows: ami-0e1e189f8efc7b9b1 }
    me-south-1 : { linux: ami-0d316edc29753567c, windows: ami-0fa5de6e8f345f842 }
    sa-east-1 : { linux: ami-0a2ef742c4534698f, windows: ami-0d476095ac9a9604a }
...
```

**Comment by yob** [comment]
Argh! Thanks for reporting, we're looking into this now

**Comment by yob** [comment]
@jufemaiz Can you try https://s3.amazonaws.com/buildkite-aws-stack/v5.0.0/aws-stack.yml again? I believe it's been fixed.

**Comment by jufemaiz** [comment]
https://s3.amazonaws.com/buildkite-aws-stack/v5.0.0/aws-stack.yml

Now has:

```yaml
...
# Generated from Makefile via build/mappings.yml
  AWSRegion2AMI:
    us-east-1 : { linux: ami-0a196d0aa9a8cdf17, windows: ami-0cb9b5cd847093398 }
    us-east-2 : { linux: ami-0249ef14f43aa6082, windows: ami-083f68c059866a416 }
    us-west-1 : { linux: ami-0e1fecc1503ffe5bf, windows: ami-012ecd3241359b510 }
    us-west-2 : { linux: ami-072d3a7f8eadafef2, windows: ami-06838ae0a5f35077a }
    af-south-1 : { linux: ami-03997fda22502f38d, windows: ami-0c062d70a9a583814 }
    ap-east-1 : { linux: ami-0c13278e2c6cf7029, windows: ami-0382782bc77000a16 }
    ap-south-1 : { linux: ami-0282d556af9440b16, windows: ami-0ca73f07bbe49fff0 }
    ap-northeast-2 : { linux: ami-09b31fc79ecc967b1, windows: ami-04d73c52facd6de59 }
    ap-northeast-1 : { linux: ami-0a1c6888551a01507, windows: ami-0b1844719f6e24449 }
    ap-southeast-2 : { linux: ami-01536d210ac41d3d8, windows: ami-0f326cf0d52106c1c }
    ap-southeast-1 : { linux: ami-057f11c9faa4f2d7d, windows: ami-0297e493188e1aa90 }
    ca-central-1 : { linux: ami-0743e57cb1af72f8b, windows: ami-039ac013dc03b49a2 }
    eu-central-1 : { linux: ami-0800a6f9ef31e2b0a, windows: ami-0c4c4bf2210706b43 }
    eu-west-1 : { linux: ami-0c5b19d8f77ac097f, windows: ami-0e28058b57f017dac }
    eu-west-2 : { linux: ami-0574acd72763935a4, windows: ami-0517b9fe57e6fca3c }
    eu-south-1 : { linux: ami-0d9a747355d42f83e, windows: ami-08017d1aa1a706cd7 }
    eu-west-3 : { linux: ami-01c20125e3ee92547, windows: ami-0bb9c0c1ae3d8573b }
    eu-north-1 : { linux: ami-036bb9355a6dac739, windows: ami-03f7d9ff7013bb028 }
    me-south-1 : { linux: ami-0b46b9926873fc864, windows: ami-056a5be468ab99c7a }
    sa-east-1 : { linux: ami-0bb0a496a65d8590f, windows: ami-0ed7a1a14b2a75749 }

...
```
