### ISSUE TITLE
Use asg warm pools for faster buildkite job starts

### ISSUE THREAD

**Issue by nitrocode** [buildkite/elastic-ci-stack-for-aws#822]
https://aws.amazon.com/about-aws/whats-new/2021/04/amazon-ec2-auto-scaling-introduces-warm-pools-accelerate-scale-out-while-saving-money/

If we could keep X instances warmed up, we could start jobs much faster without having to set the min count on the asg to something non-zero.

**Comment by chloeruka** [comment]
Woah! You're quick. Yeah this feature looks great; especially for Windows instances that take a while to boot. According to the announcement it's not yet available on Cloudformation, but when it is we'll take a look into it.

**Comment by nitrocode** [comment]
https://docs.aws.amazon.com/en_us/AWSCloudFormation/latest/UserGuide/aws-resource-autoscaling-warmpool.html

**Comment by nitrocode** [comment]
The only param that would require an additional input to use the warm pool would be the min size of it. We use an asg min size of 0 and max size of 10 so a warm pool min size of 3 seems reasonable.

The [cloudformation docs have been released](https://docs.aws.amazon.com/en_us/AWSCloudFormation/latest/UserGuide/aws-resource-autoscaling-warmpool.html).

```yaml
Resources:
  myWarmPool: 
    Type: AWS::AutoScaling::WarmPool
    Properties:
      AutoScalingGroupName: !Ref myASG
      MinSize: 30
      PoolState: Stopped
```
