### ISSUE TITLE
IAM Policy Misconfiguration 

### ISSUE THREAD

**Issue by priyaoz** [buildkite/elastic-ci-stack-for-aws#852]
I believe the [aws-stack.yaml ](https://github.com/buildkite/elastic-ci-stack-for-aws/blob/master/templates/aws-stack.yml)has 2 misconfiguration in the AWS::IAM::Poilcy 

   
```
  ManagedSecretsBucketPolicy:
    Type: AWS::IAM::Policy
    Condition: CreateSecretsBucket
    Properties:
      PolicyName: SecretsBucketPolicy
      PolicyDocument:
        Statement:
          - Effect: Allow
            Action:
              - s3:Get*
              - s3:Get
              - s3:List*
            Resource:
              - !Sub "arn:aws:s3:::${ManagedSecretsBucket}/*"
              - !Sub "arn:aws:s3:::${ManagedSecretsBucket}"
      Roles:
        - !Ref IAMRole
```

In the above snippet, there is no aws s3 action name `s3:Get` 🤔 .

Line numbers:785 & 803 in [aws-stack.yaml ](https://github.com/buildkite/elastic-ci-stack-for-aws/blob/master/templates/aws-stack.yml)
