### ISSUE TITLE
New parameter in CloudFormation template to add variable BUILDKITE_AGENT_TAGS_FROM_HOST

### ISSUE THREAD

**Issue by tinder-terrychu** [buildkite/elastic-ci-stack-for-aws#878]
Sometimes engineers may want to automatically add `hostname` tags to the agents when launching them from the CloudFormation template. Currently, this feature is not supported in the template parameters. A parameter named like `BuildkiteAgentTagsFromHost` defaulting to `false` that gets inserted into the value of environment variable `BUILDKITE_AGENT_TAGS_FROM_HOST` would really make some engineers' lives easier. 
I would be happy to help contribute to this implementation but wanted to create an issue first to run by the Buildkite staff and discuss this is appropriate.

**Comment by keithduncan** [comment]
Hi @tinder-terrychu, I’m afraid we’d strongly hesitate to add this feature to the Elastic CI Stack parameters. Using hostname to target work can be an anti-pattern which diverges from our recommended ["shared nothing" approach](https://buildkite.com/docs/agent/v3/elastic-ci-aws#what-type-of-builds-does-this-support) to CI.

We strongly encourage customers not to assume the state of the host between builds, and instead rely on [build meta-data](https://buildkite.com/docs/pipelines/build-meta-data#main) and [build artifacts](https://buildkite.com/docs/pipelines/artifacts) to pass state between steps.

The primary risk to hostname agent targeting is that between steps the host may pull work from another build in the same pipeline, or another pipeline entirely, breaking any assumptions you may have about the state of the host.

We are more than happy to guide you towards alternatives to hostname targeting suitable for your use case, please don’t hesitate to leave a comment here, or start a discussion in our shared Slack channel and we’ll come up with something that works 😁

**Comment by tinder-terrychu** [comment]
Hi @keithduncan, thank you for the detailed response. Just some more contexts for our situation, we were actually recommended by the Buildkite support staff to pinpoint our build steps to all be able to run on the same agent by utilizing the build meta-data you mentioned which contains information of the agent hostname.

Here is example how some of our build steps look like right now:
```
steps:
  - command: ".buildkite/scripts/buildkite_custom.sh"
    name: "Set Custom Buildkite Env"
    agents:
      hostname: "$BUILDKITE_AGENT_META_DATA_HOSTNAME"
  - command: ".buildkite/scripts/set_mac_time_zone.sh"
    name: "Set macOS Time Zone"
    agents:
      hostname: "$BUILDKITE_AGENT_META_DATA_HOSTNAME"
  - command: "set -euxo pipefail && git lfs pull"
    name: "Git LFS Pull"
    agents:
      hostname: "$BUILDKITE_AGENT_META_DATA_HOSTNAME"
```

I am also curious as to why for the `buildkite-agent start` command, one of the available params is `--tags-from-host` which, according to the [documentation](https://buildkite.com/docs/agent/v3/cli-start), "includes tags from the host (hostname, machine-id, os) `[$BUILDKITE_AGENT_TAGS_FROM_HOST]`". I was under the impression that this parameter is available so that users can start up an agent with the hostname tag attached to it. Wouldn't we want the same feature be available through the CloudFormation deployment anyway regardless of the intention?
