### ISSUE TITLE
Cross-region deploy made difficult when using Elastic CI stack

### ISSUE THREAD

**Issue by toothbrush** [buildkite/elastic-ci-stack-for-aws#891]
Hey folks, we've just adopted this Elastic CI stack instead of our legacy/hand-built one, and it mostly is working well!

We ran into a surprising issue though, when attempting to do a cross-region deploy.  The situation is that we rely on `AWS_DEFAULT_REGION` to point deploy commands at the right target (that's probably not the best, but bear with me, legacy decisions that are now in many repos all over the place 🤷).

One of our pipelines looks roughly as follows – commands such as `aws` inside the Makefile rely on `AWS_DEFAULT_REGION` pointing where we want to deploy things:

```yaml
steps:
  - name: us-east-1
    command: make deploy-app
    env:
      AWS_DEFAULT_REGION: 'us-east-1'
      KUBERNETES_DEPLOY_TARGET: 'https://kubernetes-production.us-east-1.our.domain'
    agents:
      queue: deploy-prod

  - name: us-west-2
    command: make deploy-app
    env:
      AWS_DEFAULT_REGION: 'us-west-2'
      KUBERNETES_DEPLOY_TARGET: 'https://kubernetes-production.us-west-2.our.domain'
    agents:
      queue: deploy-prod
```

However, when the steps run i see that in both cases, `AWS_DEFAULT_REGION == us-east-1` – that's where our Buildkite agents run.

I suspect this code is running and somehow overriding the `env:` block of our `pipeline.yml`, but there must surely be a way to allow overriding some of these variables?  

https://github.com/buildkite/elastic-ci-stack-for-aws/blob/368a03a14b51a44a87af733a96cc193c7b10a3eb/templates/aws-stack.yml#L981-L985

I've currently made a workaround for one of our repositories, but this feels like quite a footgun – if i set a value in the pipeline's `env:` block, i expect it to be respected in the executed steps.

cc: @novatan-rb @jonhiggs

**Comment by toothbrush** [comment]
I've just double-checked using a small repro:

```yaml
steps:
  - name: us-east-1
    command: env
    env:
      TEST_FOO: bar
      AWS_DEFAULT_REGION: us-east-1

  - name: us-west-2
    command: env
    env:
      TEST_FOO: baz
      AWS_DEFAULT_REGION: us-west-2
```

Concentrating on the `us-west-2` step, if i look at the "Environment" tab of the step, it looks as expected:

![image](https://user-images.githubusercontent.com/423357/129829668-a508fe7c-c425-48d1-9765-8cfaf6ca8c9a.png)

But if i look at the output of the steps, `env` disagrees:

```
[2021-08-18T02:56:04Z] $ trap 'kill -- $' INT TERM QUIT; env
[2021-08-18T02:56:04Z] BUILDKITE_CONFIG_PATH=/etc/buildkite-agent/buildkite-agent.cfg
[2021-08-18T02:56:04Z] AWS_REGION=us-east-1
[2021-08-18T02:56:04Z] AWS_DEFAULT_REGION=us-east-1
...
```

That doesn't seem right to me?

**Comment by keithduncan** [comment]
Hi @toothbrush!

The part you have linked to only sets environment variables for the `bk-install-elastic-stack.sh` script run as part of the EC2 Instance’s `UserData`. However, those environment variables do get [saved](https://github.com/buildkite/elastic-ci-stack-for-aws/blob/368a03a14b51a44a87af733a96cc193c7b10a3eb/packer/linux/conf/bin/bk-install-elastic-stack.sh#L46-L47) and subsequently [sourced](https://github.com/buildkite/elastic-ci-stack-for-aws/blob/368a03a14b51a44a87af733a96cc193c7b10a3eb/packer/linux/conf/buildkite-agent/hooks/environment#L5) by an Agent environment hook so actually will be set in your job environment by the hook and overwrite the one set by your job env 🤔 

Does it seem reasonable to tack an `AWS_DEFAULT_REGION=foo` on the end of your `make` commands which will be set as an environment variable for make-spawned subcommands?

```bash
keithduncan@Keiths-Mac-mini make-test % make target | grep 'AWS_*'
keithduncan@Keiths-Mac-mini make-test % make target AWS_DEFAULT_REGION=us-east-1 | grep 'AWS_*'
declare -x AWS_DEFAULT_REGION="us-east-1"
declare -x MAKEFLAGS="AWS_DEFAULT_REGION=us-east-1"
```

**Comment by toothbrush** [comment]
Yeah – that's one way of working around it.  I just made a patch to one of our repos to set `DEPLOY_REGION=foo` and in the Makefile re-export `export AWS_DEFAULT_REGION=${DEPLOY_REGION}` if set.  This way the workaround is obvious.  

My concern with an approach like you suggest is that the difference between the following isn't obvious at all:

```yaml
steps:
  - name: approach 1
    command: make something
    env:
      AWS_DEFAULT_REGION: us-east-1

  - name: approach 2
    command: make something AWS_DEFAULT_REGION=us-west-2
```

..and someone is liable to come along later and not realise there's a bit footgun lurking there.

Wouldn't it be preferable to patch this bit:

https://github.com/buildkite/elastic-ci-stack-for-aws/blob/368a03a14b51a44a87af733a96cc193c7b10a3eb/packer/linux/conf/bin/bk-install-elastic-stack.sh#L46-L47

Into something more like (pseudo-code, but i mean to say, use whatever `AWS_DEFAULT_REGION` is set, and only set it to the build agent's region if it's not set?

```sh
export AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION:-${REGION}}
```
