### ISSUE TITLE
v5.6.0 » Autoscaling not passing on BuildkiteAgentTokenParameterStoreKMSKey

### ISSUE THREAD

**Issue by jufemaiz** [buildkite/elastic-ci-stack-for-aws#901]
https://github.com/buildkite/elastic-ci-stack-for-aws/blob/v5.6.0/templates/aws-stack.yml#L1105-L1113

```yaml
      Parameters:
        BuildkiteAgentTokenParameter: !If [ UseCustomerManagedParameterPath, !Ref BuildkiteAgentTokenParameterStorePath, !Ref BuildkiteAgentTokenParameter ]
        BuildkiteQueue: !Ref BuildkiteQueue
        AgentsPerInstance: !Ref AgentsPerInstance
        MinSize: !Ref MinSize
        MaxSize: !Ref MaxSize
        AgentAutoScaleGroup: !Ref AgentAutoScaleGroup
        ScaleOutFactor: !Ref ScaleOutFactor
        ScaleOutForWaitingJobs: !Ref ScaleOutForWaitingJobs
```

Expected parameters of the autoscaling nested cloudwatch template:

```yaml
  BuildkiteAgentTokenParameter:
    Description: Buildkite agent token parameter
    Type: AWS::SSM::Parameter::Name
  BuildkiteAgentTokenParameterStoreKMSKey:
    Description: AWS KMS Key ID used to encrypt the SSM parameter (if encrypted)
    Type: String
    Default: ''
  BuildkiteQueue:
    Description: Queue name that agents will use, targeted in pipeline steps using "queue={value}"
    Type: String
    Default: default
    MinLength: 1
  AgentAutoScaleGroup:
    Description: The name of the autoscale group to autoscale.
    Type: String
    Default: default
  AutoscalingLambdaExecutionRole:
    Description: IAM Role ARN
    Type: String
    Default: ''
  AgentsPerInstance:
    Description: ''
    Type: Number
  MinSize:
    Description: ''
    Type: String
  MaxSize:
    Description: ''
    Type: String
  ScaleOutFactor:
    Description: ''
    Type: Number
  ScaleOutForWaitingJobs:
    Description: ''
    Type: String
    AllowedValues:
    - 'true'
    - 'false'
    Default: 'false'
```
